Controllers/EquipoController.cs
using BattleFight.Models;
using BattleFight.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BattleFight.Controllers
{
    public class EquipoController : Controller
    {

        private Service service;

        public EquipoController()

        {

            service = new Service();

        }


        // GET: EquipoController
        public ActionResult Index()
        {
            var model = service.mostrarEquipo();

            return View(model);
        }

        // POST: EquipoController/Index

        [HttpPost]

        [ValidateAntiForgeryToken]

        public ActionResult Index(string Categoria)

        {

            var model = new List<Equipo>();

            if (!string.IsNullOrEmpty(Categoria))

                model = service.filtroEquipo(Categoria);

            else model = service.mostrarEquipo();

            return View(model);

        }

        // GET:EquipoController/Details/5
        public ActionResult Details(int equipoid)
        {
            return View();
        }


        // GET: EquipoController/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: EquipoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Equipo equipo)
        {
            try
            {
                if (ModelState.IsValid)

                {
                    service.agregarEquipo(equipo);
                    return RedirectToAction("Index");
                }
            }

            catch
            { }

            return View();
        }

        // GET: EquipoController/Edit/5
        public ActionResult Edit(int equipoid)
        {
            var equipoBuscado = service.buscarEquipo(equipoid);

            return View(equipoBuscado);
           
        }

        // POST: EquipoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Equipo equipoActualizado)
        {
            try

            {
                service.actualizarEquipo(equipoActualizado);
                return RedirectToAction("Index");
            }

            catch (Exception ex)

            {

                ViewBag.Error = ex.Message;
                return View(equipoActualizado);

            }
        }

        
        
    }
}

Controllers/TorneoController.cs
using BattleFight.Models;
using BattleFight.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BattleFight.Controllers
{
    public class TorneoController : Controller
    {

        private Service service;

        public  TorneoController()
        {
            service = new Service();
        }
        // GET: TorneoController
        public ActionResult Index()
        {
            var model = service.mostrarTorneo();
            return View(model);
        }

        // GET: TorneoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TorneoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Torneo torneo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    service.agregarTorneo(torneo);
                    return RedirectToAction("Index");
                }
            }
            catch
            {}
            return View();
        }

        // GET: TorneoController/Edit/5
        public ActionResult Edit(int torneoid)
        {
            var torneoBuscado = service.buscarTorneo(torneoid);
            return View(torneoBuscado);
        }

        // POST: TorneoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Torneo torneoActualizado)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    service.actualizarTorneo(torneoActualizado);
                    return RedirectToAction("Index");

                }
            }
            catch
            {}
            return View();
        }

        // GET: TorneoController/Delete/5
        public ActionResult Delete(int torneoid)
        {
            var torneoBuscado = service.buscarTorneo(torneoid);
            return View(torneoBuscado); 
        }

        // POST: TorneoController/Delete/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int torneoid)
        {
            try
            {
                var torneoBuscado = service.buscarTorneo(torneoid);
                service.eliminarTorneo(torneoBuscado); 
                return RedirectToAction("Index"); 
            }
            catch (Exception)
            {
                return View();
            }
        }

        
        // GET: TorneoController/AsignarEquipos/5
        public ActionResult AsignarEquipos(int torneoid)
        {
            var torneo = service.buscarTorneo(torneoid);
            var equipos = service.mostrarEquiposPorCategoria(torneo.CategoriaEnfrentar);
            ViewBag.Torneo = torneo;
            return View(equipos); 
        }

        // POST: TorneoController/DeterminarGanador
        [HttpPost]
        public ActionResult DeterminarGanador(int torneoid, List<int> idsEquipos)
        {
            try
            {
                var equiposSeleccionados = service.obtenerEquiposPorIds(idsEquipos);
                var ganador = service.determinarGanador(equiposSeleccionados);

                // Actualizar el torneo con el ganador
                var torneo = service.buscarTorneo(torneoid);
                torneo.Ganador = ganador.NombreEquipo;
                service.actualizarTorneo(torneo);

                ViewBag.Ganador = ganador;
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return RedirectToAction("AsignarEquipos", new { torneoid });
            }
        }
    }
}

Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using BattleFight.Models;
using BattleFight.Services;

namespace BattleFight.Controllers
{
    public class UsuarioController : Controller
    {
        private Service service;

        public UsuarioController()
        {
            this.service = new Service();
        }

        public ActionResult Acerca()
        {
            return View();
        }
        // GET: UsuarioController
        public ActionResult Index()
        {
            var model = service.mostrarUsuarios();
            return View(model);
        }
        // GET: UsuarioController/Login
        public ActionResult Login()
        {
            return View();
        }
        // POST: UsuarioController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string user, string pass)
        {
            try
            {
                var UsuarioLogueado = service.ValidarInicioSesion(user, pass);
                HttpContext.Session.SetString("NombreUsuario", UsuarioLogueado.Nombre);
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
                
            }
            
        }

      
        // GET: UsuarioController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsuarioController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Usuario usuario)
        {
            try
            {
                // Validar contraseñas
                service.ValidarContrasenas(usuario);
                service.agregarUsuario(usuario);
                return RedirectToAction(nameof(Login)); 
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;  
                return View(usuario);

            }
        }
            

        // GET: UsuarioController/Edit/5
        public ActionResult Edit(int id)
        {
            var usuarioBuscado = service.buscarUsuario(id);
            return View(usuarioBuscado);
        }

        // POST: UsuarioController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Usuario usuarioActualizado)
        {
            try
            {
                // Validar contraseñas
                service.ValidarContrasenas(usuarioActualizado);
                service.actualizarUsuario(usuarioActualizado);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(usuarioActualizado);

            }
        }

        // GET: UsuarioController/Delete/5
        public ActionResult Delete(int id)
        {
            
                var usuarioBuscado = service.buscarUsuario(id);
            
            return View(usuarioBuscado);
        }

   
        // POST: TorneoController/Delete/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var usuarioBuscado = service.buscarUsuario(id);
                service.eliminarUsuario(usuarioBuscado);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BattleFight</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BattleFight.styles.css" asp-append-version="true" />
</head>


<div class="container">
    <!-- Agregar la imagen aquí -->
    <img src="~/images/header.jpg" alt="Logo" class="img-fluid" style="width: 100000px; height: auto;" />
</div>

<body>
    <header>
        <nav id="menu" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="nav-link battlefight-link" asp-area="" asp-controller="Home" asp-action="Index">BattleFight</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link button" asp-area="" asp-controller="Usuario" asp-action="Index"><span>Usuario</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link button" asp-area="" asp-controller="Equipo" asp-action="Index"><span>Equipo</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link button" asp-area="" asp-controller="Torneo" asp-action="Index"><span>Torneo</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link button" asp-area="" asp-controller="Home" asp-action="Acerca"><span>Acerca de</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark button-salir" asp-area="" asp-controller="Usuario" asp-action="Login">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M6.5 1a.5.5 0 0 1 .5.5v5.793l3.146-3.147a.5.5 0 0 1 .708.708L7.707 8l2.647 2.646a.5.5 0 0 1-.708.708L7 8.707V14.5a.5.5 0 0 1-1 0v-13a.5.5 0 0 1 .5-.5z" />
                                    <path fill-rule="evenodd" d="M13 8a.5.5 0 0 1-.5.5H2a.5.5 0 0 1 0-1h10.5a.5.5 0 0 1 .5.5z" />
                                </svg>
                                <span>Salir</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BattleFight
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>